resources:
  - ../../base

patches:
  - target:
      kind: Deployment
      name: guestbook-ui
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/image
        value: gcr.io/heptio-images/ks-guestbook-demo:0.1